// Dev-only test data for the application form.
// This file should be tree-shaken out of the production bundle
// because it is only imported inside a NODE_ENV === 'development' check.

export const DEV_TEST_DATA = {
  email: "test@testcompany.com",
  scheme: "seis" as const,
  companyName: "Test Company Ltd",
  companyNumber: "12345678",
  utr: "1234567890",
  incorporatedAt: "2024-01-15",
  isKic: false,
  kickReason: "",
  riskToCapital: "The company aims to grow its SaaS platform to 10,000 paying customers within 3 years, scaling from current revenue of £50,000 ARR. The business plan projects headcount growth from 3 to 15 employees. Investor capital is at risk as the company is pre-profitability and dependent on continued product development and sales execution. The long-term objective is to capture 1% of the UK SME market for compliance software.",
  qualifyingActivity: "trade" as const,
  tradeStarted: true,
  tradeStartDate: "2024-03-01",
  tradeDescription: "The company provides SaaS compliance software to UK SMEs. Revenue is generated through monthly subscriptions. Customers are small businesses in regulated industries including financial services and healthcare.",
  previousVcs: false,
  previousVcsTypes: [] as string[],
  raisingAmount: "150000",
  sharePurpose: "The funds will be used to hire two additional software engineers at £45,000 each, expand sales and marketing activities with a budget of £30,000, and invest £30,000 in product development to build new compliance modules. This directly supports the growth and development of the business.",
  proposedInvestors: [
    { name: "James Thomas", address: "14 High Street, London, SW1A 1AA", amount: "75000" },
    { name: "Sarah Williams", address: "22 Park Lane, Manchester, M1 2AB", amount: "75000" },
  ],
  shareClass: "Ordinary shares",
  preferentialRights: false,
  preferentialRightsDetail: "",
  withinInitialPeriod: "yes",
  hasSubsidiaries: false,
  grossAssetsBefore: "up_to_350k",
  grossAssetsAfter: "",
  employeeCount: "3",
  ukIncorporated: true,
  registeredAddress: { line1: "1 Test Street", line2: "", city: "London", postcode: "SW1A 1AA" },
  ukEstablishmentAddress: { line1: "", line2: "", city: "", postcode: "" },
  establishmentNarrative: "",
  hasCommercialSale: null as boolean | null,
  firstCommercialSaleDate: "",
  outsidePeriodReason: "",
  previousInvestmentAmount: "",
  previousInvestmentDate: "",
  newMarketDetails: "",
  signatoryName: "John Smith",
  signatoryPosition: "Director",
};
